services:
  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/cartsync?sslmode=disable
    ports:
      - "5050:8081"
