version: "3.9"

services:
  server:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "6300:3000"
    environment:
      DB_HOST: host-gateway
      UPLOAD_DIR: /app/uploads
    volumes:
      - uploads:/app/uploads
    extra_hosts:
      - "host-gateway:host-gateway"

volumes:
  uploads:
